# Generated by Django 6.0 on 2025-12-26 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=10)),
                ('payload', models.TextField()),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('qr_image', models.ImageField(upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
