# Generated by Django 6.0 on 2025-12-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='back_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='border',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='box_size',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='error_correction',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('Q', 'Q'), ('H', 'H')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='fill_color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='transparent_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
